<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UserSecretsId>osuforfellascomparison-local-oauth</UserSecretsId>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="BouncyCastle.Cryptography" Version="2.6.2" />
		<PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="8.0.0" />
	</ItemGroup>

</Project>
